name: RVNKQuests
version: 1.0.0
description: A quest system for Minecraft
authors: [YourName]
main: org.fourz.RVNKQuests.RVNKQuests
api-version: 1.17

commands:
  quest:
    description: Main command for the RVNKQuests plugin
    usage: /quest <subcommand> [arguments]
    aliases: [quests, q]

permissions:
  rvnkquests.command.item:
    description: Allows players to get quest items
    default: op
  rvnkquests.command.state:
    description: Allows players to change quest states
    default: op